name: Pacman Animation

on:
  schedule:
    - cron: "0 */6 * * *" # update tiap 6 jam
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pac-Man ASCII
        run: |
          echo "# Halo ðŸ‘‹" > README.md
          echo "" >> README.md
          echo "Pac-Man saya ðŸ’" >> README.md
          echo "" >> README.md
          echo '```' >> README.md
          echo "   ðŸŸ¡   ðŸ‘» ðŸ‘» ðŸ‘»" >> README.md
          echo '```' >> README.md

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update pacman"
